// 기믹 모듈 내보내기
export { Key } from './Key';
export { Lock } from './Lock';
export { Spike } from './Spike';
export { Goal } from './Goal';
export { Spring } from './Spring';
export { Elevator } from './Elevator';
export type { ElevatorConfig } from './Elevator';
export { MovableBlock } from './MovableBlock';
export type { MovableBlockConfig } from './MovableBlock';
export { Bumper } from './Bumper';
export { MovingBumper } from './MovingBumper';
export type { MovingBumperConfig } from './MovingBumper';
export { PoisonMushroom } from './PoisonMushroom';
export { BlockButton } from './BlockButton';
export type { BlockButtonConfig } from './BlockButton';
export { TogglePlatform } from './TogglePlatform';
export { TriggerButton } from './TriggerButton';
export type { TriggerButtonConfig } from './TriggerButton';
export { Signboard } from './Signboard';
export type { SignboardConfig } from './Signboard';
export { GhostPlatform } from './GhostPlatform';
