# ==========================================
# 1. ?? ?? & WebSocket ??
# ==========================================
# 9001 (Game Server Listening Port)
# Spring Boot? ? ??? ?? ??, WebSocket ??? ? ??? ?????.
server.port=9001
# ?????? ??
spring.application.name=echoforest
# ==========================================
# 2. LiveKit ?? (Signaling)
# ==========================================
# LiveKit ?? ?? (?? ?? 7880 ??)
# ?? ?? ??(HTTP)??? ws:// ?? (?? ? wss:// ??)
livekit.url=ws://localhost:7880
# LiveKit API Key
livekit.api-key=devkey
# LiveKit API Secret
livekit.api-secret=secret